language: java

script: 

- "mvn test -B"

- "mvn --show-version --errors --batch-mode clean verify"

mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - oraclejdk8
  
cache:
    directories:
    - $HOME/.m2  
    
after_success:
  - mvn coveralls:report    