language: java
dist: trusty
script:
- mvn test -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
jdk:
- oraclejdk10
addons:
apt:
packages:
- oracle-java10-installer
cache:
directories:
- $HOME/.m2
after_success:
- mvn coveralls:report
  